# Generated by Django 2.1.3 on 2018-11-20 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_auto_20181119_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='moviename',
        ),
    ]
